### ISSUE TITLE
navmesh does not work in Hubs -  Blender 4.2.2 seams not to export the navmesh component correctly

### ISSUE THREAD

**Issue by uhunkler** [Hubs-Foundation/hubs-blender-exporter#311]
When a scene is exported from Blender 4.2.2, the navmesh does not work in Hubs.

**To Reproduce**
Export a scene in Blender 4.2.2 as GLB and import it in Hubs. The navmesh is not recognised in Hubs.

I compared the exported GLTF from Blender 3.6 with the one from Blender 4.2.2 and noticed, that the component call 
          `"nav-mesh": {},`
is missing in the Blender 4.2.2 GLTF. When I add the line, create the GLB with the updated GLTF and upload that to Hubs the navmesh is recognised again.

When I look at the addons/io_hubs_addon/components/definitions/nav_mesh.py component file I don't see any special. Because I don't know how to debug the Blender AddOn I can't investigate more and hope my findings may help to solve the issue

**Comment by Exairnous** [comment]
@uhunkler Thank you for the bug report.  I have uploaded a pull request that should fix it.  Long story short, it was a change in Blender's glTF exporter that we needed to account for.  See the description in the pull request for details.
